name: Go Test

on:
  push:
    branches: [ main ]

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v3
	with:
	  go-version: '1.22'

      - name: Fetch dependencies
        run: |
	  cd src
	  go mod download

      - name: Test with Go
        run: go test -v -cover ./...